### ISSUE TITLE
Banner eagle on report page links to report.php rather than board.php

### ISSUE THREAD

**Issue by JarlenR** [shittyboard/shittyboard#1]
Would fix but I don't know php that well. Also master branch isn't open to commits?

**Comment by shittyboard** [comment]
>  eagle on report page links to report.php rather than board.php
Yes, it does, because it is poorly adopted version of shittyboard. I might change that.

>  Also master branch isn't open to commits?
I don't know.  And I don't know how GitHub (and any version control) works...

**Comment by JarlenR** [comment]
Just realised that report.php isn't in the repo so that wouldn't really help.

>I don't know how Github (and any version control) works

I don't really know it that well either, does your IDE handle it? Mine does most of it for me. I only know the basic terminology really, never had to use more than that (yet).

I believe pull requests are where you can approve each modification individually, or you can just give people you trust commit permissions, and revert changes later if they go wild and delete stuff.

**Comment by shittyboard** [comment]
> I don't really know it that well either, does your IDE handle it? 

No. I don't even know terminology.

**Comment by JarlenR** [comment]
If your IDE doesn't handle it, and you don't the terminology...

How are you updating the repository here? I see regular commits by you.

**Comment by shittyboard** [comment]
Using web interface of GitHub

**Comment by shittyboard** [comment]
Technically I use GitHub's IDE, I guess
